[package]
name = "the-winter-of-our-disconnect"
version = "0.1.0"
authors = ["Oliver Gould <ver@buoyant.io>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
log = "0.4"
pretty_env_logger = "0.3"
structopt = "0.2"
tokio = "0.1.16"
